In [1]:
from data.dataset import NgramDataset

In [2]:
obj = NgramDataset(3, "dataset.txt", 25626,3204,3203)
x,y = obj.get_complete_dataset()

In [25]:
x = torch.ones((2,3))
s = time.perf_counter()
for i in range(len(x)):
    print(x[i])
e = time.perf_counter()

tensor([1., 1., 1.])
tensor([1., 1., 1.])


In [29]:
for a,b in zip(torch.ones((2,3)),torch.zeros((2,3))):
    print(a,b)

tensor([1., 1., 1.]) tensor([0., 0., 0.])
tensor([1., 1., 1.]) tensor([0., 0., 0.])


In [3]:
import torch
rg = torch.Generator().manual_seed(0)

In [15]:
a = torch.tensor([[2,3,4],[5,6,7]]).split(2, dim=0)

In [16]:
a[0]

tensor([[2, 3, 4],
        [5, 6, 7]])